spring.application.name=audio-transcriber-backend
spring.ai.openai.api-key=
spring.ai.openai.audio.transcription.base-url=http://localhost
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.response-format=json